import Footer from "./components/Footer";
import Navbar from "./components/Navbar";
import "./globals.css";

export const metadata = {
  title: "Nasarawa State",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="font-roboto">
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
